// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27cKk83rBwU3rQWEkSPiu_BRxoG1d3_g',
    appId: '1:586305598547:web:c5e0d2fd17ae972b58c2a6',
    messagingSenderId: '586305598547',
    projectId: 'medlive-5acf4',
    authDomain: 'medlive-5acf4.firebaseapp.com',
    storageBucket: 'medlive-5acf4.appspot.com',
    measurementId: 'G-1R5BM9CD61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgY_lw6LFiopTQcflsO6tEAzjjdjh_U_k',
    appId: '1:586305598547:android:efd99c33f292ee1158c2a6',
    messagingSenderId: '586305598547',
    projectId: 'medlive-5acf4',
    storageBucket: 'medlive-5acf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHkpPqTb-Bb_QaiKykqBFoFCzEcUU2Hx4',
    appId: '1:586305598547:ios:2e2648fe35ece0d358c2a6',
    messagingSenderId: '586305598547',
    projectId: 'medlive-5acf4',
    storageBucket: 'medlive-5acf4.appspot.com',
    iosBundleId: 'com.example.medlive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHkpPqTb-Bb_QaiKykqBFoFCzEcUU2Hx4',
    appId: '1:586305598547:ios:2e2648fe35ece0d358c2a6',
    messagingSenderId: '586305598547',
    projectId: 'medlive-5acf4',
    storageBucket: 'medlive-5acf4.appspot.com',
    iosBundleId: 'com.example.medlive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD27cKk83rBwU3rQWEkSPiu_BRxoG1d3_g',
    appId: '1:586305598547:web:f0ae60e8212e1b6458c2a6',
    messagingSenderId: '586305598547',
    projectId: 'medlive-5acf4',
    authDomain: 'medlive-5acf4.firebaseapp.com',
    storageBucket: 'medlive-5acf4.appspot.com',
    measurementId: 'G-8C53YR1PVV',
  );
}
